spring:
  profiles:
    active: prod
mybatis:
  mapper-locations:
    - classpath*:mapper/**/*.xml
  configuration-properties:
    schema: hugh
logging:
    level:
      root: info
      com.uwjx.department.testing.mapper: trace